spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              #              uri: http://user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**

            - id: product-service
              #              uri: http://user-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/**

            - id: order-service
              #              uri: http://user-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**

            - id: eureka-dashboard-home
              uri: ${EUREKA_SERVER_URL:http://localhost:8761}
              predicates:
                - Path=/eureka
              filters:
                - SetPath=/

#            - id: eureka-home-static
#              uri: ${EUREKA_SERVER_URL:http://localhost:8761}
#              predicates:
#                - Path=/eureka/**
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
